[general]
working_directory = "C:\\Users\\Nine"
import = ["C:\\Users\\Nine\\.config\\alacritty\\one-dark.toml"]

[env]
TERM = "xterm-256color"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[cursor]
blink_interval = 650
blink_timeout = 0

[cursor.style]
shape = "Block"
blinking = "On"

[terminal.shell]
program = "C:\\Program Files\\Git\\bin\\bash.exe"
args = ["--login", "-i"]
